name: "food_desert_stl"
version: "1.0.0"
config-version: 2

profile: "food_desert_stl"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  food_desert_stl:
    staging:
      +materialized: view
    marts:
      +materialized: table
